dataset=

get: $(dataset).tar.bz2 construct clean

construct:
	mkdir -p $(dataset)
	tar -xjvf $(dataset).tar.bz2

bibtex.tar.bz2:
	wget https://www.dropbox.com/s/yizjmqxi6ulub3y/bibtex.tar.bz2

sector.tar.bz2:
	wget https://www.dropbox.com/s/9qhaxn9rxb0n4mq/sector.tar.bz2

rcv1_regions.tar.bz2:
	wget https://www.dropbox.com/s/be6sit7zcxxy4uw/rcv1_regions.tar.bz2

aloi.bin.tar.bz2:
	wget https://www.dropbox.com/s/jwousxredtggq3y/aloi.bin.tar.bz2

Dmoz.tar.bz2:
	wget https://www.dropbox.com/s/lq6vd7t6nz1w7iy/Dmoz.tar.bz2

Eur-Lex.tar.bz2:
	wget https://www.dropbox.com/s/swjyqbtxea1q1mp/Eur-Lex.tar.bz2

LSHTC1.tar.bz2:
	wget https://www.dropbox.com/s/0mgarujfps4cb78/LSHTC1.tar.bz2

LSHTCwiki.tar.bz2:
	wget https://www.dropbox.com/s/3j8urvy6j9kyx4u/LSHTCwiki.tar.bz2

imageNet.tar.bz2:
	wget https://www.dropbox.com/s/898cgz76lmuz04a/imageNet.tar.bz2

clean:
	rm $(dataset).tar.bz2
